Nicer sample debug (#5)
When running the sample code from `README.md` I got a lot of similar error messages:

```
./bin/eet_ping.rb:43:in `<main>': undefined method `dat_odmit' for #<EET_CZ::Response::Success:0x007f8ecb241f60> (NoMethodError)
```

That is mainly because [printing out sample response](https://github.com/ciihla/ruby-eet-cz/blame/master/README.md#L59-L67) calls all the possible fields no matter what type of response we got.

This PR modifies the example, so that is just dumps whole response.