Time.zone is nil (#4)
When running sample code from `README.md`, I get following error:

```
$ bundle exec ruby ./bin/eet_ping.rb
./bin/eet_ping.rb:28:in `<main>': undefined method `now' for nil:NilClass (NoMethodError)
```

Not sure where is the root of the problem problem, but just using `Time.current` as stated in section [16.1.1 in active_support docs](http://guides.rubyonrails.org/active_support_core_extensions.html#extensions-to-time) fixed my problem.